### ISSUE TITLE
Why are typeguards using toString instead of typeof?

### ISSUE THREAD

**Issue by nexxeln** [LuciNyan/ts-known#2]
What is the reason to use the `toString` function and then check the output instead of using typeof?

```ts
// current implementation
export function isObject(x: unknown): x is object {
  return toString(x) === '[object Object]'
}

// with typeof
export function isObject(x: unknown): x is object {
  return typeof x === "object" && x !== null;
}
```

**Comment by kfirfitousi** [comment]
`toString` gives more information than typeof.

```ts
typeof new Date // "object"
toString(new Date) // "[object Date]"

typeof null // "object" (WHY JAVASCRIPT? WHY??)
toString(null) // "[object Null]"
```

**Comment by LuciNyan** [comment]
Hi @nexxeln! Thank you for raising this interesting question! I have the same opinion as @kfirfitousi. And I wonder if we could change the return type of isObject to `x is Record<PropertyKey, unknown>`. This could make it more meaningful. What do you think?

<img width="498" alt="image" src="https://user-images.githubusercontent.com/22126563/222618605-cbc3fdf2-72fa-49e0-9f6d-82dfd1010dba.png">
